name: PvPToggle
version: 1.1
description: Toggles PvP for people
author: [Cheezychicken]
contributor: [Mats1300]
website: https://github.com/NerdNu/PvPToggle
main: com.cheezychicken.pvptoggle.PvPToggle
api-version: 1.20

depend: [WorldGuard, TAB]

commands:
  pvp:
    description: Toggle a player's PvP status
    permission: pvp.toggle
    usage: /pvp [on|off|persist|list]

permissions:
  pvp.toggle:   
    description: Allow use of /pvp command
  pvp.others:
    description: Allow users to change pvp status of other people
