name: PvPToggle
version: ${project.version}
description: Toggles PvP for people

author: cheezychicken
website: ${project.url}
main: com.cheezychicken.pvptoggle.PvPToggle
api-version: 1.16

depend: [WorldGuard, NametagEdit]

commands:
  pvp:
    description: Toggle a player's PvP status
    permission: pvp.toggle
    usage: |
           /<command> on - Turns PvP on for the player
           /<command> on persist - Turns PvP on for the player. This will persist through death.
           /<command> off - Turns PvP off for the player
           /<command> list - Lists players with PvP on

permissions:
  pvp.toggle:   
    description: Allow use of /pvp command
  pvp.others:
    description: Allow users to change pvp status of other people
